apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "model-face-detect3"
  namespace: "ai-dept"
spec:
  default:
    predictor:
      tensorflow:
        storageUri: "pvc://kfserving-pvc-ehs3/models/face_detection3"

