apiVersion: v1
kind: Pod
metadata:
  name: pod-espcn
  namespace: "kubeflow"
spec:
  volumes:
  - name: data-sr-espcn
    persistentVolumeClaim:
      claimName: pvc-espcn
  containers:
    - name: container-espcn
      image: rauleun/ai-kubeflow:ver6
      resources:
        requests:
          memory: "2Gi"
          cpu: "0.7"
        limits:
          memory: "5Gi"
          cpu: "1"
      command: ["/bin/sh", "-c", "while : ; do sleep 3; done"]
      volumeMounts:
        - mountPath: /hd
          name: data-sr-espcn

