apiVersion: v1
kind: PersistentVolume
metadata:
  name: kfserving-pv-ehs3
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: csi-cephfs-sc 
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /home
