apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata:
  namespace: ai-dept
  labels:
    controller-tools.k8s.io: "1.0"
  name: katib-sr-ex1
spec:
  objective:
    type: maximize
    goal: 0.5
    objectiveMetricName: PSNR
  metricsCollectorSpec:
    collector:
      kind: StdOut
  algorithm:
    algorithmName: bayesianoptimization
  parallelTrialCount: 1
  maxTrialCount: 5
  maxFailedTrialCount: 3
  parameters:
    - name: --learning_rate
      parameterType: double
      feasibleSpace:
        min: "0.0001"
        max: "0.0003"
        step: "0.00001"
  trialTemplate:
    goTemplate:
        rawTemplate: |-
          apiVersion: "kubeflow.org/v1"
          kind: TFJob
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
           tfReplicaSpecs:
            Worker:
              replicas: 1
              restartPolicy: OnFailure
              template:
                spec:
                  volumes:
                    - name: sr-data
                      persistentVolumeClaim:
                        claimName: pvc-sr-data
                  containers:
                    - name: tensorflow
                      image: rauleun/ai-kubeflow:ver3
                      volumeMounts:
                      - name: sr-data
                        mountPath: /hd
                      imagePullPolicy: Always
                      resources:
                        requests:
                          cpu: 0.7
                          memory: 10Gi
                          nvidia.com/gpu: 1
                        limits:
                          cpu: 0.8
                          memory: 20Gi
                          nvidia.com/gpu: 1
                      command:
                        - "python"
                        - "/home/super_resolution-module_SR_VESPCN/tf2/srcs/trainers/espcn/espcn_trainer_gradient_tape.py"
                        - "--exp_name=youtube_small_data_scale2_00_epoch10_gradient_tape_lr1e-4_hyunsung"
                        {{- with .HyperParameters}}
                        {{- range .}}
                        - "{{.Name}}={{.Value}}"
                        {{- end}}
                        {{- end}}
                      
