apiVersion: v1
kind: Pod
metadata: 
  name: pod-katib
  namespace: "kubeflow"
spec:
  volumes:
  - name: data-espcn 
    persistentVolumeClaim:
      claimName: pvc-katib
  containers:
    - name: container-katib
      image: rauleun/ai-kubeflow:ver7 
      resources:
        requests:
          memory: "2Gi"
          cpu: "0.7"
        limits:
          memory: "3Gi"
          cpu: "1"
      volumeMounts:
        - mountPath: /hd
          name: data-espcn
      command: ["/bin/sh", "-c", "while : ; do sleep 3; done"]

